version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: rrhh_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - rrhh_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./rrhh-backend
      dockerfile: Dockerfile
    container_name: rrhh_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      PORT: 4000
    ports:
      - "${BACKEND_PORT}:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./rrhh-backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./rrhh-frontend
      dockerfile: Dockerfile
    container_name: rrhh_frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:${BACKEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    volumes:
      - ./rrhh-frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  rrhh_pgdata:
  backend_node_modules:
  frontend_node_modules: